<?php

namespace Lk\EntManipsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlopRepository extends EntityRepository
{
}
