<?php

namespace Lk\EntManipsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagadaRepository extends EntityRepository
{
}
